[workspace]
members = ["crates/rustafari-core", "crates/rustafari-app"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/David-Portillo/rustafari"
homepage = "https://github.com/David-Portillo/rustafari"
authors = ["David Portillo"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
